### ISSUE TITLE
[참고] Intellij & docker & network (05.22 실습 - window 버전)

### ISSUE THREAD

**Issue by LimPark996** [LimPark996/TIL#13]
**PostgreSQL을 활용한 지난 시간 복습**

강의 자료: https://github.com/LimPark996/boot-container-review/tree/main
 
1. intellij 를 킨다. application-prod 복붙 -> application-dev 생성한다.
2. intellij community 버전인 경우, dbeaver에서 postgreSQL 데이터베이스를 생성한다.
- 이때, application-dev 파일의 datasource와 postgreSQL 데이터베이스 설정 정보가 일치해야 된다.

```
--application-dev 파일 상단 코드--

  # 데이터소스
  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver # MySQL
    driver-class-name: org.postgresql.Driver # PostgreSQL
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: rootpass
``` 

- application-prod 파일도 조심해야 된다!

```
--application-prod 파일 상단 코드--

  # 데이터소스
  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver # MySQL
    driver-class-name: org.postgresql.Driver # PostgreSQL
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
```

3. docker desktop이나 rancher desktop을 킨다.
4. 터미널에 아래 순서로 명령어를 친다. (만약 이후에 postman에서 POST 형태로 localhost:8080/api/pet (body 추가) 했는데 500이 뜬다면 둘의 순서를 바꿔봐도 된다)

```
docker run -d -p 5432:5432 --name postgres -e POSTGRES_PASSWORD=rootpass postgres:16-alpine
docker build -t my-boot:postgres -f Dockerfile .
```

### 몹시 주의: 4번 실행 전에는 Springboot 실행을 꼭 꺼놔야 된다.

**이유**

1. 포트 충돌

로컬 Spring Boot: 8080 포트 사용
Docker 컨테이너: 8080 포트를 8989로 매핑
둘 다 실행되면 PostgreSQL 5432 포트도 충돌 가능

2. 데이터베이스 연결 혼란

로컬 앱: localhost:5432로 연결 시도
Docker 앱: postgres:5432로 연결 시도 (컨테이너 네트워크 내에서)

**Comment by LimPark996** [comment]
**위 코드들을 실행한 후에는 이게 꼭 되어야 한다.**

1. Postman 확인

![Image](https://github.com/user-attachments/assets/0e1370bc-4ce7-4b1e-8fdf-e4e64728e052)

2. dbeaver (community 버전) 내 데이터 구성 확인

![Image](https://github.com/user-attachments/assets/1705cdfa-a22c-4faa-86cf-78d71f340216)

**Comment by LimPark996** [comment]
**네트워크로 넘어가기 전에, 왜 저렇게 해야 되는지 상세 분석을 해본다**

### 1. 빌드하는 과정에서 어떤 현상이 일어나는가?

**빌드 코드**

```
docker build -t my-boot:postgres -f Dockerfile .
```

**이 코드는 각각 무엇을 의미하는가?**

무엇을 하는가:

현재 디렉토리의 Dockerfile을 읽어서
Java 애플리케이션을 컨테이너 이미지로 패키징
my-boot:postgres라는 이름으로 저장

각 부분의 의미:

**docker build** - Docker 이미지를 빌드하는 명령어
**-t my-boot:postgres** - 생성될 이미지의 이름:태그 지정
**-f Dockerfile** - 사용할 Dockerfile 파일명 지정 (생략 가능)
**.** - 빌드 컨텍스트 (현재 디렉토리)

### 2. 실행하는 과정에서 어떤 현상이 일어나는가?

**실행 코드**

```
docker run -d -p 5432:5432 --name postgres -e POSTGRES_PASSWORD=rootpass postgres:16-alpine
```

**이 코드는 각각 무엇을 의미하는가?**

실행 결과:

PostgreSQL 16 서버가 컨테이너에서 시작
localhost:5432로 접근 가능
사용자명: postgres, 비밀번호: rootpass
백그라운드에서 계속 실행

네트워크 관련:
현재 명령어에는 --network 옵션이 없어서 기본 네트워크에 연결됩니다. Spring Boot 컨테이너와 통신하려면 같은 네트워크에 있어야 하므로 --network db-network를 추가해야 합니다!

각 부분의 의미:

docker run

Docker 컨테이너를 생성하고 실행하는 명령어

**-d (detached)**

백그라운드에서 실행 (데몬 모드)
터미널이 컨테이너에 연결되지 않음
컨테이너 ID만 출력하고 프롬프트로 돌아옴

**-p 5432:5432 (port mapping)**

포트 포워딩 설정
호스트포트:컨테이너포트
로컬 PC의 5432 포트 → 컨테이너의 5432 포트로 연결
외부에서 localhost:5432로 접근하면 컨테이너 내부 PostgreSQL에 연결

**--name postgres**

컨테이너에 이름 부여
이름 없으면 Docker가 랜덤하게 생성
다른 컨테이너에서 postgres라는 이름으로 참조 가능

**-e POSTGRES_PASSWORD=rootpass**

환경변수 설정
PostgreSQL의 postgres 사용자 비밀번호를 rootpass로 설정
PostgreSQL 이미지가 요구하는 필수 환경변수

**postgres:16-alpine**

Docker 이미지 지정
postgres: PostgreSQL 공식 이미지
16: PostgreSQL 버전 16
alpine: Alpine Linux 기반 (경량화된 버전)


**-d 유무의 실제 차이:**

-d 없이 실행 (Foreground)

터미널이 컨테이너의 stdout/stderr에 연결됨
PostgreSQL 프로세스가 터미널 세션에 종속됨
터미널 닫으면 → 컨테이너 종료됨
Ctrl+C 누르면 → 컨테이너 종료됨

-d 사용 (Detached)

터미널과 분리된 상태로 실행
컨테이너가 독립적으로 백그라운드에서 실행
터미널 닫아도 → 컨테이너 계속 실행됨

**왜 run을 사용하나요?**

docker run은 **"컨테이너 생성 + 시작"**을 한 번에 하는 명령어입니다.

run의 장점:

한 번에 컨테이너 생성하고 시작
설정(포트, 환경변수, 네트워크 등)을 생성과 동시에 적용
대부분의 사용 사례에서 가장 편리함

**-d는 단순히 로그 출력 문제가 아니라, 터미널과의 연결을 끊어서 독립적으로 실행하기 위한 옵션입니다. 서버 애플리케이션처럼 계속 실행되어야 하는 경우에는 거의 필수적으로 사용합니다!**

**Comment by LimPark996** [comment]
**기본 네트워크가 아니라 db-network에 연결해보자**

postgres 이미지는 이미 빌드되어 있다는 전재 하에 진행한다.

```
docker rm -f postgres
docker run -d -p 5432:5432 --name postgres  --network db-network  -e POSTGRES_PASSWORD=rootpass  postgres:16-alpine                                        
docker rm -f boot-container-250522
docker run -d -p 8989:8080 --name boot-container-250522  --env-file .env --network db-network my-boot:postgres
docker ps
docker logs boot-container-250522
``` 

### 일단 이 코드들을 실행시키면 어떻게 될까? -> 같은 네트워크 안에 있는 상황!

**기본 개념을 연결지어서 생각해본다.**

**컨테이너는 각자 독립된 공간**입니다.

```
┌─────────────────┐    ┌─────────────────┐
│  postgres       │    │ boot-container  │
│  컨테이너       │    │  컨테이너       │
│                 │    │                 │
│  (독립된 공간)  │    │  (독립된 공간)  │
└─────────────────┘    └─────────────────┘
```

**localhost의 의미**

**localhost = 자기 자신**을 가리킵니다.

- `postgres` 컨테이너에서 `localhost` = postgres 컨테이너 자기 자신
- `boot-container` 컨테이너에서 `localhost` = boot-container 컨테이너 자기 자신

**문제 상황**

boot-container가 데이터베이스에 연결하려고 할 때:

**❌ 잘못된 방법:**
```
boot-container에서 localhost:5432로 연결 시도
→ 자기 자신(boot-container) 안에서 5432 포트를 찾음
→ postgres는 다른 컨테이너에 있으니까 못 찾음
→ 연결 실패!
```

**✅ 올바른 방법:**
```
boot-container에서 postgres:5432로 연결 시도  
→ Docker가 "postgres"를 postgres 컨테이너로 연결해줌
→ 연결 성공!
```

---

### 왜 이게 가능했을까?

**코드가 만드는 상황**

**1단계: postgres 컨테이너 생성**
```bash
docker run -d -p 5432:5432 --name postgres --network db-network ...
```
- `postgres`라는 이름의 컨테이너 생성
- `db-network`에 연결

**2단계: boot-container 생성**  
```bash
docker run -d -p 8989:8080 --name boot-container-250522 --network db-network ...
```
- `boot-container-250522`라는 이름의 컨테이너 생성
- 같은 `db-network`에 연결

**결과: 두 컨테이너가 서로 이름으로 찾을 수 있음**

```
     db-network
┌─────────────────────────┐
│                         │
│  ┌─────────────┐       │    ┌─────────────────┐
│  │  postgres   │       │    │ boot-container  │
│  │             │ ←──── │ ── │                 │
│  │  :5432      │       │    │  postgres:5432  │
│  └─────────────┘       │    │  로 연결 가능!  │
│                         │    └─────────────────┘
└─────────────────────────┘
```

**핵심은 `--network db-network`**:
- 이 옵션 때문에 두 컨테이너가 같은 네트워크에 속함
- boot-container에서 `postgres:5432`로 연결 가능
- `postgres`가 컨테이너 이름이자 주소 역할

---

### 코드에서 8989:8080이 의미하는 바?

**포트 매핑의 의미**

호스트포트:컨테이너포트 형식입니다.

```
8989:8080
 ↓     ↓
호스트  컨테이너
포트   내부포트
```

**실제 동작**

```
┌─── 내 컴퓨터 (호스트) ───┐
│                        │
│  8989포트              │     ┌─ boot-container ─┐
│   ↓                    │     │                  │
│   연결통로 ─────────────┼────→│  8080포트        │
│                        │     │  (Spring Boot)   │
└────────────────────────┘     └──────────────────┘
```

**구체적인 예시**

외부에서 접속할 때:

브라우저에서 localhost:8989 입력
Docker가 자동으로 boot-container의 8080포트로 연결

**왜 이렇게 하나요?**

컨테이너 내부에서는 Spring Boot가 8080포트에서 실행 중
하지만 외부에서는 8989포트로 접속
포트 충돌 방지 + 여러 컨테이너 동시 실행 가능

**정리:**

localhost:8989 ← 외부에서 접속하는 주소
8080 ← 컨테이너 안에서 Spring Boot가 실제 사용하는 포트

---

### 포트 충돌이 무엇일까?

**포트 충돌이란?**

**상황**: Spring Boot 애플리케이션 2개를 동시에 실행하고 싶다면?

**❌ 포트 매핑 없이 실행하면:**
```bash
# 첫 번째 컨테이너
docker run -d --name app1 my-spring-app
# 두 번째 컨테이너  
docker run -d --name app2 my-spring-app
```

둘 다 컨테이너 내부에서 8080포트 사용 → 외부에서 어떻게 구분?

**포트 매핑으로 해결**

**✅ 포트 매핑 사용:**
```bash
# 첫 번째 앱
docker run -d -p 8989:8080 --name app1 my-spring-app

# 두 번째 앱  
docker run -d -p 9090:8080 --name app2 my-spring-app
```

**결과:**
```
내 컴퓨터 (호스트)
├── localhost:8989 → app1 컨테이너의 8080포트
└── localhost:9090 → app2 컨테이너의 8080포트
```

**실제 사용**

- `localhost:8989` 접속 → 첫 번째 앱
- `localhost:9090` 접속 → 두 번째 앱
- 둘 다 내부적으로는 8080포트 사용하지만 외부에서는 다른 포트로 접근

**즉, 호스트의 포트를 다르게 해서 여러 컨테이너를 동시에 실행할 수 있어요!**

**Comment by LimPark996** [comment]
**docker compose를 하려면?**

### 근데 왜 docker compose를 쓸까?

이전 단계에서는 네트워크 만들어서 도커 실행 시, 아래와 같은 단점들이 있었다.  

```
명령어가 너무 길고 복잡함
실행 순서를 기억해야 함
네트워크도 따로 만들어야 함
컨테이너 하나씩 관리해야 함
```

docker compose를 쓰면.. 아래 명령어 하나로 압축된다.

```
docker compose up
```

---
### docker compose up을 하기 위해서 필요한 것 -> docker-compose.yml

Dockerfile 과 같은 Depth에 docker-compose.yml을 넣는다.

docker-compose.yml 예시는 아래와 같다.

```
services:
    app:
      build: .
      ports:
        - "${APP_PORT}:8080"
      env_file:
        - ".env"
      networks:
        - "guini-network"
      depends_on:
        - postgresql
      command: ["sh", "-c", "sleep10 && java -jar app.jar"]
    postgres:
      image: "postgres:16-alpine"
      env_file:
        - ".env"
      ports:
        - "${DB_PORT}:5432"
      volumes:
        - "db-data:/var/lib/postgresql/data"
      networks:
        - "guini-network"
volumes:
  db-data:

networks:
  guini-network:
```

.env도 수정이 필요하다.

```
DB_URL=jdbc:postgresql://postgres:5432/postgres
DB_USERNAME=postgres
DB_PASSWORD=rootpass
APP_PORT=18787
DB_PORT=15432
POSTGRES_PASSWORD=rootpass
```

이후 아래 명령어를 친다

```
docker compose up
```
---
### Docker Compose vs 기존 명령어 비교

```
# === 이 부분이 docker build -t my-boot:postgres -f Dockerfile . ===
services:
    app:
      build: .                               # 현재 폴더 Dockerfile로 빌드

# === 이 부분이 docker run postgres 명령어 ===
    postgres:
      image: "postgres:16-alpine"            # postgres:16-alpine 이미지 사용
      env_file:
        - ".env"                             # -e POSTGRES_PASSWORD=rootpass 대신 .env 파일 사용
      ports:
        - "${DB_PORT}:5432"                  # -p 5432:5432 와 동일
      networks:
        - "guini-network"                    # --network db-network 와 동일

# === 이 부분이 docker run boot-container 명령어 ===
    app:
      ports:
        - "${APP_PORT}:8080"                 # -p 8989:8080 와 동일 (8989는 .env의 APP_PORT)
      env_file:
        - ".env"                             # --env-file .env 와 동일
      networks:
        - "guini-network"                    # --network db-network 와 동일
      depends_on:
        - postgres                         # postgres 먼저 실행 (docker rm -f 후 순서대로 실행하는 것과 비슷)

# === 이 부분이 docker network create db-network (자동 생성) ===
networks:
  guini-network:                             # db-network 대신 guini-network 이름 사용
```

결과적으로:

기존: 5개 명령어를 순서대로 실행
Compose: docker compose up 한 번으로 모든 작업 완료!

이름만 다른 것:

db-network → guini-network
boot-container-250522 → app
