### ISSUE TITLE
[참고] prometheus + 수신 웹후크 (05.26 실습 - window 버전)

### ISSUE THREAD

**Issue by LimPark996** [LimPark996/TIL#15]
**프로메테우스의 또다른 활용처**

시간이나 메모리 등 어떠한 용량이 임계값을 넘었을때, alert 를 사용하면 알람을 받을 수 있다.

구체적으로는 alert와 Slack 수신 웹후크를 활용하면 Slack 으로 alert 메시지 알림을 받을 수 있다.

---

단계별로 설명하자면, 

1. Slack -> 왼쪽에서 "앱추가"를 클릭한다.
2. 검색창이 뜰거다. Incoming WebHooks를 검색한다.
3. 채널 선택하여 알림을 뜨는데 연동할 채널을 선택한다. (미리 새 채널을 만들어두고 진행하는 것도 좋다)
4. "수신 웹후크 통합 앱 추가" 버튼을 누른다.
5. 아래와 같이 웹후크 URL을 찾을 수 있다.
```
https://hooks.slack.com/services/...
```
6. 이제 인텔리지로 돌아간다.

아래 저장소에서 코드를 clone 하거나, 활용한다.

https://github.com/LimPark996/boot-prom-review

7. alertmanager.yml 파일의 app_url에 5번에서 가져온 웹후크 URL을 넣는다.
8. alertmanager.yml 파일의 channel에 채널명을 넣는다.
9. Spring Boot를 실행한다.
10. 아래 명령어를 터미널에 친다.

```
docker run -d -p 9090:9090 -v ${pwd}/prometheus.yml:/etc/prometheus/prometheus.yml -v ${pwd}/alert.rules.yml:/etc/prometheus/alert.rules.yml --name prometheus prom/prometheus:latest  #prometheus, alert.rules 컨테이너 생성

docker run -d -p 9093:9093 -v ${pwd}/alertmanager.yml:/etc/alertmanager/alertmanager.yml --name alertmanager prom/alertmanager:latest #alertmanager 컨테이너 생성

 .\load-test.ps1 -Threads 10 -Duration 30 -Host localhost -Port 8080 -Path "/200"  #10개의 작업자가 30초 동안 요청 반복 수행 
```

---

**부하테스트 명령어 설명**

```
 .\load-test.ps1 -Threads 10 -Duration 30 -Host localhost -Port 8080 -Path "/200"
```

실제 동작:
10개의 작업자가 30초 동안 다음을 수행:

각자 http://localhost:8080/200에 요청
10ms 간격으로 요청 반복
각 스레드당 약 3000개 요청 (30초 ÷ 0.01초)
총 약 30,000개 요청

**alert.rules : 알림이 뜨는 임계치 설정**

```
groups:
  - name: example
    rules:
      - alert: HighRequestRate
        expr: rate(http_server_requests_seconds_count[15s]) > 0.1  # 매우 낮은 임계값
        for: 5s
        labels:
          severity: warning
        annotations:
          summary: "Request rate high"
```

전체 동작 흐름:

매 순간 체크: Prometheus가 rate(http_server_requests_seconds_count[15s]) > 0.1 조건 확인
조건 만족: 초당 0.1개 이상 요청이 오면 → PENDING 상태
5초 지속: PENDING 상태가 5초 지속되면 → FIRING 상태 (알람 발생)
알람 전송: Alertmanager가 Slack 등으로 알람 전송
